public: true
type: "docs"
tags:
  - "social media"
  - "social media team"
  - "policy"
title: "Social Media Policy"
description: "A policy for creating and sharing content using the RAC's social media platforms."
